[package]
name = "super_mmpbsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.6.0"
xdrfile = "^0.3.0"
toml = "^0.5.2"
ndarray = "^0.15.6"
indicatif = "^0.17.1"
